import json

with open("lista_compras.json") as f:  
    bd = json.load(f)

ontologia = """
################################################################
#    Individuals
#################################################################
"""

for lista in bd:
    lista_id = lista['designacao'].replace(" ","_")

    ontologia += f"""
###  http://rpcw.di.uminho.pt/2026/compras#{lista_id}
:{lista_id} rdf:type owl:NamedIndividual ,
                :ListaCompras ;
        :designacao "{lista['designacao']}" ;
        :data "{lista['data']}" .
"""

    for prod in lista['produtos']:  
        prod_id = prod['designacao'].replace(" ", "_")
        cat_id = prod['categoria'].replace(" ","_")
    
        ontologia += f"""
###  http://rpcw.di.uminho.pt/2026/compras#{cat_id}
:{cat_id} rdf:type owl:NamedIndividual ,
                :Categoria .

###  http://rpcw.di.uminho.pt/2026/compras#{prod_id}
:{prod_id} rdf:type owl:NamedIndividual ,
                :Produto ;
        :temCategoria :{cat_id} ;
        :designacao "{prod['designacao']}" ;
        :valor "{prod['quantidade']['valor']}" ;
        :unidade "{prod['quantidade']['unidade']}" .

:{lista_id} :temProduto :{prod_id} .            
"""
    
ontologia += f"""
###  Generated by RPCW2026 script 2026/02/06
"""    

print(ontologia)