import json

with open("myManifest.json") as f:  
    bd = json.load(f)

ontologia = """@prefix : <http://rpcw.di.uminho.pt/2026/manifesto#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

#################################################################
#    Individuals
#################################################################
"""

for manifesto in bd:
    titulo_id = manifesto['titulo'].replace(" ","_")

    ontologia += f"""
###  http://rpcw.di.uminho.pt/2026/manifesto#{titulo_id}
:{titulo_id} rdf:type owl:NamedIndividual ,
                :TPC ;
        :titulo "{manifesto['titulo']}" ;
        :data "{manifesto['data']}" .
"""

    for autor in manifesto['autor']:  
        autor_id = autor['id']
        autor_nome_uri = autor['nome'].replace(" ","_")
    
        ontologia += f"""
###  http://rpcw.di.uminho.pt/2026/manifesto#{autor_id}
:{autor_id} rdf:type owl:NamedIndividual ,
                :Autor ;
        :temNome "{autor['nome']}" ;
        :temId "{autor['id']}" .

:{titulo_id} :temAutor :{autor_id} .
"""
    
ontologia += f"""
###  Generated by RPCW2026 script 2026/02/06
"""    

print(ontologia)